services:
  # O código da nossa API
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - api_network
    depends_on:
      - postgres
      - redis

  # Banco de Dados
  postgres:
    image: postgres:16-alpine
    container_name: api_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api_network

  # Servidor Web
  nginx:
    image: nginx:alpine
    container_name: api_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api_network
    depends_on:
      - app

  # Cache e Sessões
  redis:
    image: redis:alpine
    container_name: api_redis
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
